# Etapa de build
FROM golang:1.22-alpine AS builder

WORKDIR /app

COPY go.mod ./
RUN go mod download

COPY . ./

RUN CGO_ENABLED=0 GOOS=linux go build -o /currency-converter ./cmd/server

# Etapa final
FROM alpine:latest

WORKDIR /root/

COPY --from=builder /currency-converter .

EXPOSE 8080

CMD ["./currency-converter"]
