version: "3.8"

services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: currency
      POSTGRES_PASSWORD: currency123
      POSTGRES_DB: converter
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  app:
    build:
      context: ../..
      dockerfile: deployments/docker/Dockerfile
    environment:
      PORT: 8080
    ports:
      - "8080:8080"
    depends_on:
      - db
      - rabbitmq

volumes:
  pg_data:
